language: swift
osx_image: xcode8.0
script:
  - xctool -project Conductor.xcodeproj -scheme Conductor -sdk iphonesimulator clean build test
  - xctool -project Conductor.xcodeproj -scheme Conductor clean build test
